export const PATHS = {
    home: "/",
    trending: "/trending",
    community: "/community",
    subscriptions: "/subscriptions",
    playlists: "/playlists",
    history: "/history",
    liked: "/liked",
    watchLater: "/watch-later",
    upload: "/upload",
    dashboard: "/dashboard",
    aiSearch: "/ai/search",
    aiChat: "/ai/chat",
    settings: "/settings",
    login: "/login",
    register: "/register",
    forgotPassword: "/forgot-password",
    resetPassword: "/reset-password",
    notFound: "*",
};
