/**
 * Offline fallback catalogue for AnimeVerse.
 *
 * This list intentionally stores ONLY a stable search title (plus a few aliases
 * where punctuation/branding commonly differs). It is not pretending to be a
 * metadata authority. When AniList/Jikan are unavailable, these titles give the
 * YouTube importer enough trustworthy identity to discover official promo
 * material. Unknown synopsis/genre/studio/year fields stay empty rather than
 * being fabricated.
 *
 * Existing AniList/Jikan documents are title-deduplicated before any row from
 * this list is inserted. Synthetic ids live in a reserved negative namespace and
 * are never exposed as real AniList ids.
 */

export const CURATED_ANIME_CATALOG = [
    // Action / shonen / mainstream series
    { key: "black-clover", title: "Black Clover" },
    { key: "fairy-tail", title: "Fairy Tail" },
    { key: "sword-art-online", title: "Sword Art Online" },
    { key: "fire-force", title: "Fire Force" },
    { key: "bungo-stray-dogs", title: "Bungo Stray Dogs" },
    { key: "tokyo-revengers", title: "Tokyo Revengers" },
    { key: "hells-paradise", title: "Hell's Paradise" },
    { key: "kaiju-no-8", title: "Kaiju No. 8", aliases: ["Kaiju No 8"] },
    { key: "wind-breaker", title: "WIND BREAKER" },
    { key: "mashle", title: "MASHLE: MAGIC AND MUSCLES", aliases: ["Mashle"] },
    { key: "zom-100", title: "Zom 100: Bucket List of the Dead", aliases: ["Zom 100"] },
    { key: "noragami", title: "Noragami" },
    { key: "soul-eater", title: "Soul Eater" },
    { key: "d-gray-man", title: "D.Gray-man" },
    { key: "inuyasha", title: "Inuyasha" },
    { key: "rurouni-kenshin", title: "Rurouni Kenshin" },
    { key: "saint-seiya", title: "Saint Seiya" },
    { key: "blue-exorcist", title: "Blue Exorcist" },
    { key: "seraph-of-the-end", title: "Seraph of the End" },
    { key: "akame-ga-kill", title: "Akame ga Kill!", aliases: ["Akame ga Kill"] },
    { key: "seven-deadly-sins", title: "The Seven Deadly Sins" },
    { key: "magi", title: "Magi: The Labyrinth of Magic", aliases: ["Magi"] },
    { key: "undead-unluck", title: "Undead Unluck" },
    { key: "shangri-la-frontier", title: "Shangri-La Frontier" },
    { key: "sakamoto-days", title: "SAKAMOTO DAYS", aliases: ["Sakamoto Days"] },
    { key: "gachiakuta", title: "Gachiakuta" },

    // Fantasy / isekai / adventure
    { key: "slime-isekai", title: "That Time I Got Reincarnated as a Slime" },
    { key: "mushoku-tensei", title: "Mushoku Tensei: Jobless Reincarnation", aliases: ["Mushoku Tensei"] },
    { key: "overlord", title: "Overlord" },
    { key: "konosuba", title: "KONOSUBA -God's blessing on this wonderful world!", aliases: ["KonoSuba"] },
    { key: "no-game-no-life", title: "No Game No Life" },
    { key: "eminence-in-shadow", title: "The Eminence in Shadow" },
    { key: "shield-hero", title: "The Rising of the Shield Hero" },
    { key: "danmachi", title: "Is It Wrong to Try to Pick Up Girls in a Dungeon?", aliases: ["DanMachi"] },
    { key: "log-horizon", title: "Log Horizon" },
    { key: "grimgar", title: "Grimgar of Fantasy and Ash", aliases: ["Grimgar"] },
    { key: "ancient-magus-bride", title: "The Ancient Magus' Bride" },
    { key: "delicious-in-dungeon", title: "Delicious in Dungeon" },
    { key: "ranking-of-kings", title: "Ranking of Kings" },
    { key: "made-in-abyss", title: "Made in Abyss" },
    { key: "land-of-lustrous", title: "Land of the Lustrous" },

    // Thriller / sci-fi / darker series
    { key: "monster", title: "Monster" },
    { key: "psycho-pass", title: "PSYCHO-PASS", aliases: ["Psycho-Pass"] },
    { key: "parasyte", title: "Parasyte -the maxim-", aliases: ["Parasyte"] },
    { key: "death-parade", title: "Death Parade" },
    { key: "erased", title: "ERASED", aliases: ["Boku dake ga Inai Machi"] },
    { key: "86-eighty-six", title: "86 EIGHTY-SIX", aliases: ["86 Eighty-Six"] },
    { key: "vivy", title: "Vivy -Fluorite Eye's Song-", aliases: ["Vivy"] },
    { key: "summer-time-rendering", title: "Summer Time Rendering" },
    { key: "heavenly-delusion", title: "Heavenly Delusion" },
    { key: "pluto", title: "PLUTO", aliases: ["Pluto"] },
    { key: "devilman-crybaby", title: "DEVILMAN crybaby", aliases: ["Devilman Crybaby"] },
    { key: "future-diary", title: "The Future Diary", aliases: ["Mirai Nikki"] },
    { key: "another", title: "Another" },
    { key: "higurashi", title: "Higurashi: When They Cry", aliases: ["When They Cry"] },
    { key: "madoka-magica", title: "Puella Magi Madoka Magica", aliases: ["Madoka Magica"] },
    { key: "serial-experiments-lain", title: "Serial Experiments Lain" },
    { key: "ergo-proxy", title: "Ergo Proxy" },
    { key: "ghost-in-shell-sac", title: "Ghost in the Shell: Stand Alone Complex" },
    { key: "black-lagoon", title: "Black Lagoon" },
    { key: "hellsing-ultimate", title: "Hellsing Ultimate" },
    { key: "claymore", title: "Claymore" },

    // Fate / supernatural / ensemble
    { key: "fate-zero", title: "Fate/Zero" },
    { key: "fate-stay-night-ubw", title: "Fate/stay night: Unlimited Blade Works", aliases: ["Fate Stay Night Unlimited Blade Works"] },
    { key: "bakemonogatari", title: "Bakemonogatari" },
    { key: "durarara", title: "Durarara!!", aliases: ["Durarara"] },
    { key: "baccano", title: "Baccano!", aliases: ["Baccano"] },
    { key: "haruhi", title: "The Melancholy of Haruhi Suzumiya" },
    { key: "golden-kamuy", title: "Golden Kamuy" },
    { key: "kingdom", title: "Kingdom" },
    { key: "legend-galactic-heroes", title: "Legend of the Galactic Heroes" },
    { key: "space-dandy", title: "Space Dandy" },

    // Sports / competition
    { key: "kuroko-basketball", title: "Kuroko's Basketball", aliases: ["Kuroko no Basket"] },
    { key: "slam-dunk", title: "Slam Dunk" },
    { key: "hajime-no-ippo", title: "Hajime no Ippo" },
    { key: "ace-of-diamond", title: "Ace of Diamond" },
    { key: "initial-d", title: "Initial D" },
    { key: "yuri-on-ice", title: "Yuri!!! on ICE", aliases: ["Yuri on Ice"] },
    { key: "free-iwatobi", title: "Free! - Iwatobi Swim Club", aliases: ["Free!"] },
    { key: "sk8-infinity", title: "SK8 the Infinity" },
    { key: "food-wars", title: "Food Wars! Shokugeki no Soma", aliases: ["Food Wars"] },
    { key: "chihayafuru", title: "Chihayafuru" },

    // Drama / romance / slice of life / comedy
    { key: "oshi-no-ko", title: "Oshi no Ko", aliases: ["[Oshi No Ko]"] },
    { key: "apothecary-diaries", title: "The Apothecary Diaries" },
    { key: "bocchi-rock", title: "BOCCHI THE ROCK!", aliases: ["Bocchi the Rock"] },
    { key: "lycoris-recoil", title: "Lycoris Recoil" },
    { key: "horimiya", title: "Horimiya" },
    { key: "toradora", title: "Toradora!", aliases: ["Toradora"] },
    { key: "fruits-basket-2019", title: "Fruits Basket (2019)", aliases: ["Fruits Basket 2019"] },
    { key: "clannad", title: "Clannad" },
    { key: "angel-beats", title: "Angel Beats!", aliases: ["Angel Beats"] },
    { key: "bunny-girl-senpai", title: "Rascal Does Not Dream of Bunny Girl Senpai" },
    { key: "oregairu", title: "My Teen Romantic Comedy SNAFU", aliases: ["Oregairu"] },
    { key: "wotakoi", title: "Wotakoi: Love Is Hard for Otaku", aliases: ["Wotakoi"] },
    { key: "komi", title: "Komi Can't Communicate" },
    { key: "skip-and-loafer", title: "Skip and Loafer" },
    { key: "blue-period", title: "Blue Period" },
    { key: "march-lion", title: "March Comes in Like a Lion" },
    { key: "nana", title: "NANA", aliases: ["Nana"] },
    { key: "beck", title: "BECK: Mongolian Chop Squad", aliases: ["BECK"] },
    { key: "bakuman", title: "Bakuman." },
    { key: "great-teacher-onizuka", title: "Great Teacher Onizuka", aliases: ["GTO"] },
    { key: "nichijou", title: "Nichijou" },
    { key: "saiki-k", title: "The Disastrous Life of Saiki K." },
    { key: "grand-blue", title: "Grand Blue Dreaming", aliases: ["Grand Blue"] },
    { key: "k-on", title: "K-ON!", aliases: ["K-On!"] },
    { key: "sound-euphonium", title: "Sound! Euphonium" },
    { key: "carole-tuesday", title: "Carole & Tuesday" },
    { key: "kids-on-slope", title: "Kids on the Slope" },
    { key: "odd-taxi", title: "ODDTAXI", aliases: ["Odd Taxi"] },
    { key: "great-pretender", title: "GREAT PRETENDER", aliases: ["Great Pretender"] },
    { key: "beastars", title: "BEASTARS", aliases: ["Beastars"] },

    // Films: high-recognition catalogue expansion
    { key: "akira", title: "AKIRA", aliases: ["Akira"] },
    { key: "grave-fireflies", title: "Grave of the Fireflies" },
    { key: "howls-moving-castle", title: "Howl's Moving Castle" },
    { key: "ponyo", title: "Ponyo" },
    { key: "weathering-with-you", title: "Weathering with You" },
    { key: "suzume", title: "Suzume" },
    { key: "i-want-eat-pancreas", title: "I Want to Eat Your Pancreas" },
    { key: "garden-of-words", title: "The Garden of Words" },
    { key: "perfect-blue", title: "Perfect Blue" },
    { key: "paprika", title: "Paprika" },
    { key: "wolf-children", title: "Wolf Children" },
    { key: "belle", title: "BELLE", aliases: ["Belle"] },
    { key: "redline", title: "REDLINE", aliases: ["Redline"] },
    { key: "girl-leapt-through-time", title: "The Girl Who Leapt Through Time" },
    { key: "summer-wars", title: "Summer Wars" },
    { key: "5-centimeters", title: "5 Centimeters per Second" },
    { key: "boy-and-heron", title: "The Boy and the Heron" },
    { key: "promare", title: "Promare" },
    { key: "children-who-chase-lost-voices", title: "Children Who Chase Lost Voices" },
    { key: "maquia", title: "Maquia: When the Promised Flower Blooms", aliases: ["Maquia"] },
    { key: "penguin-highway", title: "Penguin Highway" },
    { key: "words-bubble-soda-pop", title: "Words Bubble Up Like Soda Pop" },
    { key: "dragon-ball-super-broly", title: "Dragon Ball Super: Broly" },
    { key: "jujutsu-kaisen-0", title: "Jujutsu Kaisen 0" },
    { key: "demon-slayer-mugen-train", title: "Demon Slayer -Kimetsu no Yaiba- The Movie: Mugen Train", aliases: ["Demon Slayer Mugen Train"] },
    { key: "one-piece-red", title: "ONE PIECE FILM RED", aliases: ["One Piece Film Red"] },
];

export const CURATED_ANIME_TARGET_CAPACITY = CURATED_ANIME_CATALOG.length;
